language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script: yarn test:unit
    - stage: build
      script: yarn build
    - stage : deploy
      deploy:
        provider: heroku
        api_key:
          secure: aeWJXuGHFEQnww/wm+CBqHZ39XmVmYJoDxbYsDguIjJspIJucjyhx2gTU58vAJsKHHLAp4PCsHXCtyzEaauQDNRfxFHnpw6oVPusr+yLEq8FD3Vebrv/HYbcDJ6hmkGTLQCj+1HHuSJi6XtgEM5AQlkk15Jv9V6ON07a27N79e0Xb81N/UR4R76OaFEV7SYkVd/uM09x8D2oKVDcPrtUPnoGfIGOouS2adIhwCC8CsQG43ttqlgwEPg6JbsEVkLN3VUlG14Rw31wUNODQpJ85OZQ/e0/lnEnCpQRqxplwn2842/Ew1cXhY4jNunpoG3Bpzz8cgWymWaK7IatT0Le5FrDjB+H1EPO77DCglKTfZp21B83aBT5gkNKeexSecnX6l9go6y3g0sJ8rcWAbxHIGriNWQ6Jhznq2hJoV54oz0IJm+askPD7EYFdkY+FCWu5UQb4tglCnL4FxeAAJD3SMXShncX6xE03P+qklA2zy1K/GxuOdAe0tIR08ACNjt+lTu9MjP8yX+M2SpFlPUm4DCnH38f8SF84r42VKjom865nP7zUUsQsflKfkSeWpB4tTiJGtZjBHJ9jbPs/JsO2Yf/vwA92YW+MhaSsKwGaea6oV+RiWZGuyZZKDTDuj9a3ypURXva+dnmSX/FQoxXmd3p1nwSEZz8hOqha8NAzUM=
        app: apc-code-app
on:
  branch: master
  